require('dotenv').config();
const { notarize } = require('electron-notarize');

exports.default = async function notarizing(context) {
  const { electronPlatformName, appOutDir } = context;  
  if (electronPlatformName !== 'darwin') {
    return;
  }

  const appName = context.packager.appInfo.productFilename;

  //app-specific password generated by Apple 
  const password = 'xxxx-xxxx-xxxx-xxxx';

  return await notarize({
    appBundleId: 'com.yourcompany.applewood',
    appPath: `${appOutDir}/${appName}.app`,
    appleId: 'yourappledevid',
    appleIdPassword: password
  });
};
